<!DOCTYPE HTML>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Encode+Sans+Condensed:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <link rel="icon" type="image/svg+xml" href="" />
	<link rel="stylesheet" href="..\assets\css\styles.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>contracultura.cc</title>
  </head>
	<body>
		<div id="container">
			<!-- CABECERA -->
			<header id="header" class="header">
        		<div class="menu__wrapper">
					<div class="menu__bar">
						<img class="menu-icon" src="../assets/img/burger-menu.svg" title='Burger Menu' alt='Burger Menu'
						onclick="toggleMenu(this)">
						<ul class="navigation">
							<li>
								<a href="index_articulos.php" title="Articles">
								Artículos
								</a>
							</li>
							<li>
								<a href="index_nosotrxs.php" title="Collections">
								Consejo editorial
								</a>
							</li>
							<li>
								<a href="index_tienda.php" title="Shop">
								Tienda
								</a>
							</li>
						</ul>
					</div>
    			</div>
				<div class="header__up">
					<h1 class="header__up-name"><a href="index_maqueta.php">contracultura.cc</a></h1>
				</div>
				<div class="header__logos">
					<div class="box">
						<input
							class="search"
							placeholder=" "
							spellcheck="false"
						>
					</div>
					<img class="user-icon" src="../assets/img/user.png" alt="" id="userIcon" />
					<ul class="submenu" id="submenu">
						<form class="submenu__login" action="#" method="post">
							<label for="email">Email</label>
							<input type="email" name="email" />
							<label for="password">Contraseña</label>
							<input type="password" name="password" />
							<input class="button__enviar" type="submit" value="Login" />
						</form>
						<ul class="submenu__pedidos">
							<li><a href="#">Mis pedidos</a></li>
						</ul>
					</ul>
				</div>
    		</header>

			<!--  CONTENIDO CENTRAL -->
			<div class="articulo__container">
                <img src="../assets/img/art-biden.jpeg" alt="">
                <h1>Las consecuencias económicas del neokeynesianismo</h1>
                <p><strong>Texto de Jamie Merchant para The Brooklyn Rail. Traducción del inglés de Alfonso Fernández</strong></p>
                <p>Lo que puede leerse a continuación es la traducción de una breve reseña que Karl Kautsky publicara en Die Neue Zeit allá por 1885. Existen algunas razones por las que merecía ser traducida. La primera, que no por vaga y general resulta menos cierta, es la brutal irrelevancia a la que Karl Kautsky ha sido condenado, un hombre que durante buena parte de su vida gozó de una autoridad casi incuestionable, no sólo como representante cualificado de la “teoría marxista”, sino, incluso, como su auténtico y verdadero fundador[1]. Kautsky fue, con permiso del viejo Engels, el principal responsable de la síntesis y difusión de una obra, la de Marx, desperdigada en decenas de libros, artículos y manuscritos, algunos de los cuales acabarían conformando varias de las que hoy destacan entre sus principales obras. La flagrante traición de Kautsky como dirigente socialista a partir del verano de 1914, aquella que le haría merecedor del sobrenombre de “renegado”, ha opacado su larga trayectoria como papa del marxismo, como líder intelectual de toda una fase de desarrollo del proletariado como clase. Leerlo es una cuestión que apela, no tanto al imperativo de evaluar su figura con magnanimidad –una que podrá despertar la simpatía de unos y el odio fulgurante de otros–, sino, más bien, al rigor que se le presupone a cualquiera que se inmiscuya en el legado intelectual de una tradición de la que nos reconocemos herederos.</p>
                <p>La segunda razón es el propio contenido del texto. Lo que Kautsky está discutiendo es una determinada interpretación de la teoría del valor y la teoría del desarrollo histórico de Marx. Es evidente, entonces, que la interpretación que Kautsky hiciera de este asunto resultaba vinculante para su comunidad de lectores, conformada nada menos que por la vanguardia socialista del proletariado europeo. Los peculiares vicios de su lectura, el énfasis o infraestimación de determinados aspectos de la teoría de Marx, al margen del que pudiera ser su valor científico intrínseco, iban a configurar un cierto marco conceptual que acabaría permeando la atmósfera ideológica del socialismo de finales del siglo XIX y principios del XX. Cuando Kautsky escribió la reseña sólo habían transcurrido dos años desde la muerte de Marx, faltaba un año para la publicación de ‘La doctrina económica de Marx’ y dos para la publicación de artículos como ‘Socialismo de juristas’, textos ambos donde se elaboran motivos presentes en esta reseña. Y ello en plena batalla intelectual, pero sobre todo política, por la definición del significado del proyecto socialista. La oportunidad que brinda esta traducción para explorar algunos supuestos y posibilidades de la teoría del valor de Marx y su relación con aquel proyecto es una tercera razón, y es a la que inspira este comentario.</p>
                <div class="articulo__composicion">
                    <div class="articulo__normal-text">
                        <p>El objetivo de la intervención de Kautsky es demostrar, frente a la arbitrariedad de la versión que ofrece Gustav Groß, la unidad indisociable de las dimensiones científico-sistemática y la puramente política de la obra de Marx. Tal y como la entiende Kautsky, esta ha de servir, no sólo para comprender las leyes económicas que gobiernan el mundo capitalista, sino, sobre todo, para deducir de esta comprensión la necesidad de transformarlo en un sentido revolucionario. Es aquí donde reside, a mi juicio, lo verdaderamente interesante. ¿Cómo argumenta Marx la necesidad de esta revolución social? ¿Cómo deducir racionalmente de las leyes de la sociedad la transformación de su estructura económica? En definitiva, ¿cómo puede la crítica de la economía política fundamentar nuestra acción política?</p>
                        <p>Kautsky parece tener claro, ante todo, que el materialismo histórico no se hace cargo de ningún tipo de prescripción normativa. No impone ningún deber sobre la historia, sino que constata en ella hechos y tendencias. Y en el examen de esta cuestión introduce algunas apreciaciones sobre la teoría del valor, de la que Kautsky afirma que “no tiene nada que ver con el socialismo”.Esta afirmación revela algunas asunciones más o menos extendidas sobre el sentido de la teoría del valor de Marx. Si Kautsky es tajante al afirmar que esta no tiene nada que ver con el socialismo es porque entiende que su función es constatar cómo se produce el valor en la sociedad capitalista y, a lo sumo, constatar también que el valor contiene implícita una relación de explotación. Como se sabe, este presupone una relación de explotación de clase sostenida sobre la extracción de plusvalor: los asalariados trabajan para el capital durante más tiempo del necesario para reproducir su propia fuerza de trabajo. Kautsky, correctamente, quiere señalar que la diferencia entre salario y plusvalor no puede, por sí misma, fundamentar la necesidad de una revolución comunista. Y no puede por la sencilla razón de que la diferencia entre trabajo necesario y plustrabajo, objetivados en salario y plusvalor, sólo aparece como criterio de transformación social desde una perspectiva moral, una perspectiva para la que aquella diferencia resulta injustasólo porque subjetivamente presupone un criterio abstracto de justicia: el de la identidad o igualdad entre el tiempo de trabajo aportado y el producto retribuido, fundamento de todas las ilusiones sobre “el fruto íntegro del trabajo” de las que hablara Marx en sus glosas al programa del partido obrero alemán (1979).</p>
                    </div>
                    <div class="articulo__text"><i>"Los peculiares vicios de su lectura, el énfasis o infra- estimación de determinados aspectos de la teoría de Marx, al margen del que pudiera ser su valor científico intrínseco, iban a configurar un cierto marco conceptual que acabaría per- meando la atmósfera ideológica del socialismo de finales del siglo XIX y principios del XX"</i></div>
                </div>
                <p>La teoría del valor, una vez se entiende como una teoría limitada a explicar el origen del valor de las mercancías y el secreto de la explotación, no puede fundamentar la necesidad de transitar al socialismo, una necesidad que no es moral, sino histórica. En consecuencia, todavía restaría señalar, según plantea Kautsky citando a Engels, cuál es la razón en la cosa misma, o sea, el factor de desarrollo interno al modo de producción que justifica el comunismo objetivamente, y no en relación a un ideal moralista de justicia. Este factor interno y objetivo sería el colapso inevitable del modo de producción capitalista. </p>
                <p>Kautsky tiene razón en ambas cuestiones por separado: por un lado, en que la “injusticia” de la explotación proporciona sólo un motivo subjetivo que, por ende, como razón resulta insuficiente, arbitraria o “ideológica”; por otro, tiene razón en que la motivación objetiva y racional es el colapso histórico del capitalismo como modo de producción. Sin embargo, su comprensión torcida de la teoría del valor de Marx no permite comprender la relación interna entre ambos aspectos, la relación entre valor (tiempo de trabajo cristalizado), explotación (extracción de plusvalor) y revolución o socialismo (crisis histórica del modo de producción capitalista). Sostengo, contra Kautsky, que la teoría de Marx no niega el vínculo entre valor y socialismo, sino que, por el contrario, trata de demostrar que en el valor ha de estar contenido, al menos de manera implícita, el despliegue histórico que conduce de la actual relación de explotación de clase a la sociedad que distribuye el tiempo total de trabajo conforme a fines racionales. Esto supone que la comprensión limitada de la teoría del valor compromete igualmente la conceptualización del colapso del capitalismo y, por ende, la unidad entre sistema e historia, economía y política, que Kautsky quiere defender en su reseña. Intentaré exponer esta idea en los párrafos que siguen.</p>
                <p>Partimos de la idea básica de que la especie humana coordina el gasto de fuerza de trabajo entre los distintos miembros de la sociedad. La forma de coordinar los órganos del trabajo social, ergo la distribución del tiempo de trabajo entre los distintos miembros de la sociedad, es históricamente variable –puede darse mediante el intercambio entre propietarios privados de mercancías, mediante el uso de siervos, esclavos, etc.—, mientras que su sustancia o contenido, el gasto de fuerza de trabajo abstractamente humana como condición de reproducción de nuestra especie, es común a cualquier modo de producción. Esta última es una propiedad transhistórica, aunque no por ello externa al curso objetivo de la historia. Con el propósito de diferenciar entre contenidos transhistóricos y contenidos ahistóricos (o falsos contenidos, meras apariencias), Marx emplea una distinción metodológicamente fundamental entre lo que Richard Gunn denomina “abstracción determinada”, que encierra un contenido objetivo, y “abstracción formal”, que es responde a una operación vacía. Es en rechazo de este último tipo de abstracción que Marx exclamó aquello de “yo no parto de conceptos, ni por tanto tampoco del concepto de valor” (2022: 31).  El punto de vista de Marx, entonces, que “concibe el desarrollo de la formación económica social como un proceso histórico natural”, no parte de la abstracción indeterminada de valor o del concepto de valor “en sí mismo”, un punto de partida que resultaría arbitrario y, por ende, íntimamente dogmático.</p>
                <p>Esa es la razón por la que Kautsky, con buen criterio, condena la pretensión de establecer un concepto genérico y ahistórico de valor que, como simple representación mental, sólo puede ser formal y vacío, carente de contenido histórico. Marx rechaza esta abstracción para situarse en lo que en otro lugar denomina “concreto real” (1971: 21), el concretum de una formación social. Y es en este concretum donde Marx identifica ciertos rasgos transhistóricos que son característicos de la especie humana en cuanto tal, o sea, rasgos que definen qué significa ser individuo de esa especie bajo cualquier circunstancia histórica (y no uno de la especie “gato”, “perro” o “geranio”). Es en ese sentido que Marx es marcadamente naturalista –o, por emplear un término más amable, marcadamente “aristotélico”–, pues entiende que cada especie natural contiene predicados, funciones o modos de actividad que vienen dados para los individuos que la encarnan, y de los cuales estos últimos simplemente no pueden desvincularse: el individuo vivo actualiza, en el sentido aristotélico de energeia, las potencias propias de su especie o “forma de vida”. </p>
                <p>Pero el aristotelismo de Marx no es reduccionista: no pretende reducir las distintas formas históricas y sociales a una presunta base natural. Su punto de vista es histórico-natural, lo cual supone aceptar que la naturaleza es susceptible de desarrollo histórico, especialmente en lo que respecta al caso del ser humano. Marx entiende que el desarrollo histórico es constitutivo de la especie homo sapiens, para la que la reproducción, a diferencia de la reproducción de otras especies, cuyas necesidades y formas de actividad permanecen más o menos inmóviles con el transcurso de las generaciones, es susceptible de un progreso. Marx se refiere a esta realidad como reproducción ampliada, según la cual las necesidades, y con ellas el radio de actividad al alcance del individuo humano, se multiplica y refinamia de acuerdo con fines que son ellos mismos un producto de esa peculiar forma de reproducción (que podríamos denominar simplemente “historia”). La historia consiste en la evolución de los órganos que median nuestro metabolismo con la naturaleza (fuerzas productivas) y la consecuente actualización de las formas de interacción mediante las que este metabolismo se ejecuta (relaciones de producción). Esto explica por qué para Marx no tiene el más mínimo sentido tratar de reducir el valor de cambio al trabajo que contiene, o, más en general, tratar de reducir las formas fenoménicas desarrolladas a su sustancia original. Marx no quiere demostrar que las mercancías, el dinero y el capital encierran o esconden trabajo. Eso es una premisa autoevidente, el supuesto de cualquier posible demostración en este campo científico. Sí que pretende, en cambio, capturar conceptualmente el desarrollo de las formas históricas en las que se despliega y articula esa sustancia, demostrar la necesidad de las formas en las que se actualiza el tiempo de la vida humano:  valor de cambio, dinero, capital, salario, renta o interés, cuyo conjunto orgánico conocemos como modo de producción capitalista.</p>
                <div class="articulo__composicion-reverso">
                    <div class="articulo__normal-text">
                        <p>El naturalismo así comprendido esquiva el marcado carácter ahistórico del “concepto de valor”, sin tener que reducir por ello el valor a un dato bruto, asimilable al resto de fenómenos de la naturaleza física. El valor es una ley, un patrón social de medida que se impone, no como una causa material externa, sino como la norma que regula la distribución del tiempo total de trabajo entre los integrantes de una sociedad; es una norma que la sociedad se autoimpone, una norma que define qué es la vida humana en virtud de lo que esta hace de sí misma. Por lo tanto, el valor no es algo que sucede como sucede el movimiento de los planetas, el aumento de la temperatura o el dolor de cabeza tras una noche de libertinaje y diversión. Es algo que hacemos a la hora de actualizar o realizar los atributos característicos de nuestra especie. Esto no sólo permite comprender por qué como ley está sujeta a una evolución a través de diferentes formas históricas. Permite comprender también cuál es la función prescriptiva que tiene reservada la teoría del valor en Marx. No se trata, desde luego, de una prescripción utópica –“yo no he construido jamás un sistema socialista” (2022: 15)—, y Kautsky tiene razón cuando señala que el objeto de la teoría revolucionaria no es tanto una sociedad virtual a la que tendríamos derecho, sino la realidad efectiva de la sociedad que existe de hecho. Y es precisamente eso lo que le empuja a decir que la ley del valor no tiene nada que ver con el socialismo.</p>
                        <p>Sin embargo, existe un sentido en el que la ley del valor sí tiene que ver con el socialismo, un sentido en el que ejerce una función prescriptiva y no sólo descriptiva. Hay que tener en cuenta, en primer lugar, que el socialismo sólo es inteligible, desde la perspectiva histórico-natural de Marx, en tanto actualización de potencias contenidas en la especie humana. Esto significa: potencias contenidas en la forma realmente efectiva en la que esta se reproduce física y socialmente, el conjunto de fuerzas productivas y relaciones sociales acumuladas en el modo de producción capitalista. La principal de todas ellas es la reducción del tiempo de trabajo necesario, cuyo anacronismo como medida de la riqueza se corresponde con el desarrollo material del aparato técnico y productivo de la sociedad y con la superfluidad creciente del proletariado como instrumento vivo de la producción. Marx puede apelar por este camino a la posibilidad real del socialismo sin necesidad de introducir ad hoc una esencia humana ahistórica o una reserva antropológica cargada de posibilidades infinitas. Lo que el modo de producción capitalista revela, además de la posibilidad material del socialismo, es la obligatoriedad de organizar el tiempo de trabajo social entre todos los miembros de la sociedad –entre todos los individuos de la especie, por insistir en el lenguaje naturalista–. El valor refleja esta obligatoriedad, esta necesidad práctica, que Marx señala en una de sus cartas a Kugelmann: “es self evident que esta necesidad de la distribución del trabajo social en determinadas proporciones no puede de ningún modo ser destruida por una determinada forma de producción social; únicamente puede cambiar la forma de su manifestación. Las leyes de la naturaleza jamás pueden ser destruidas”. </p>
                        </div>
                    <div class="articulo__text-reverso"><i>"La forma de coordinar los órganos del trabajo social, ergo la distribución del tiempo de trabajo entre los distintos miembros de la sociedad, es históricamente variable –puede darse mediante el intercambio entre propietarios privados de mercancías—, mientras que su sustancia o contenido, el gasto de fuerza de trabajo abstractamente humana como condición de reproducción de nuestra especie, es común a cualquier modo de producción."</i></div>
                </div>
                <p>El socialismo, entonces, representa una forma de coordinar la producción social que hace transparente la obligatoriedad de invertir una parte del tiempo de vida en producir los medios necesarios para la subsistencia y reproducción ampliada de la sociedad, así como la obligatoriedad de distribuir el tiempo de trabajo entre sus miembros. La práctica y conciencia humanas sólo han sabido explicitar sus supuestos implícitos de forma ideológica y contradictoria, por medio de la dominación de clase y la sujeción ciega de los productores al proceso de producción. Con el capitalismo emergen por primera vez las condiciones para explicitar racionalmente este contenido: “El valor de la mercancía no hace más que expresar en una forma históricamente progresiva lo que ya existía en todas las demás formas históricas de sociedad, aunque bajo otra forma: el carácter social del trabajo en cuanto aplicación de la fuerza social del trabajo” (Marx, 2022: 42).</p>
                <p>Al comprender esta peculiar “ley de la naturaleza”, al conocer la ley que gobierna su reproducción, el ser humano puede al fin dominar las potencias de su especie, o sea, transformar el modo históricamente específico en el que aquella ley se manifiesta, haciendo de los instrumentos de producción y las relaciones sociales, no un medio de dominio sobre los demás, sino un medio para el despliegue de las capacidades físicas y espirituales de todos y cada uno –despliegue que sustituye al tiempo de trabajo como medida o patrón social de la riqueza. Este es un ideal de humanidad que no es antropológico ni idealista, el de un ser genérico o Gattungswesen que ejercita y desarrolla las capacidades que le son propias (tal y como Marx hereda del concepto aristotélico de felicidad o eudaimonía). Este es un ideal que no necesita sustraerse al curso efectivo de la historia para descubrir en ella la necesidad de un ordenamiento justo, conforme a la razón, de la vida social. Es un ideal inmanente, una finalidad inscrita en los procesos históricos objetivos. Y es este mismo ideal, tomado como regla práctica interna a la reproducción humana, el que permite evitar el riesgo del mecanicismo manifiesto de fórmulas como “colapso inevitable del modo de producción capitalista”, coherentes con el materialismo embrutecido de Kautsky, que constata hechos y tendencias como quien constata que está lloviendo o que le duele la cabeza, y para el que la revolución se impone con necesidad metafísica, o sea, al margen de la forma y el contenido de la práctica humana y de las razones que la animan. </p>
                <p>Por supuesto, este es un hilo argumental complejo y sujeto a muchísimas discusiones de matiz, que aquí no puede presentarse con la exhaustividad requerida. Valgan estos apuntes como invitación a una lectura atenta del texto de Kautsky, a la discusión de las implicaciones de la teoría del valor de Marx y de la crítica de la economía política en general.</p>
                <p><i>– Notas del comentario introductorio:</i></p>
                <p>[1] En este sentido, es recomendable la obra recién editada de Monserrat Galcerán (2023), donde tuve la suerte de saber de la existencia de esta reseña de Kautsky.</p>
                <p>[2] Es decir, allí donde las objeciones no se basan en la confusión de valor y precio, suelen basarse en la incomprensión del carácter histórico de la forma-mercancía, que es equiparada con los bienes o valores de uso. (N. de T.)</p>
                <p><i>– Bibliografía del comentario introductorio:</i></p>
                <p>Galcerán, M., La invención del marxismo, Traficantes de sueños, Madrid, 2023.</p>
                <p>Marx, K., Crítica al Programa de Gotha, Ediciones en Lenguas Extranjeras,</p>
                <p>Pekín (Beijing), República Popular China, 1979.</p>
                <p>Marx, K., Elementos fundamentales para la crítica de la economía política 1, Siglo XXI, Madrid, 1971.</p>
                <p>Marx, K., Notas sobre Wagner. Manuscritos (1861-1863), Editorial Dos Cuadrados, Madrid, 2022.</p>
                <div class="articulo__line"></div>
                <p><strong>Kautsky – “Gustav Groß, Karl Marx. Un estudio”</strong> (Leipzig, Duncker & Humblot. VI, p. 82)</p>
                <p><strong>Traducción de</u>: Paula Basterra</strong>
                <p>En la primera edición del año pasado discutimos una biografía de Lassalle que apareció en la “Biografía general alemana” [Allgemeine deutsche Biographie]. Hoy tenemos ante nosotros un trabajo sobre Marx que fue impulsado con el mismo empeño. Esta vez, sin embargo, nos encontramos en la agradable situación de poder emitir un juicio más favorable sobre la segunda que sobre la primera. El Dr. Groß ha hecho justicia a su tarea en la medida en que las circunstancias en las que ha trabajado se lo permitían. Los errores que ha cometido se deben probablemente a esas circunstancias. El Dr. Groß es jurista y profesor en una universidad alemana. Como jurista, carece del sentido histórico indispensable para comprender la doctrina de Marx; como profesor alemán, las fuerzas motrices del desarrollo político y social le son ajenas, y todo revolucionario le parece naturalmente un monstruo. No es de extrañar que al Dr. Groß le resulte imposible “identificar al Marx líder del partido con el Marx erudito. El hombre que escribe esos manifiestos y discursos provocativos y sangrientos no es para mí el mismo que el pensador profundo que escribió ‘La crítica de la economía política’ y ‘El capital’”.  Mediante esta teoría de las dos almas, el autor divide los escritos de Marx en dos grupos separados, los científicos y los de agitación, una división según un punto de vista muy externo y poco acertado. El Dr. Groß podría igualmente haber dividido las obras de Marx en delgadas y gruesas según el número de páginas. El ‘Dieciocho de brumario’, por ejemplo, se cuenta entre los escritos de agitación, ¡cuyo espíritu está supuestamente en total contradicción con las obras científicas de Marx!</p>
                <p>El autor se vio sobre todo afectado por sus cualidades de profesor alemán y jurista en el tratamiento del “Manifiesto comunista”. Este Manifiesto constituye la quintaesencia del sistema histórico de Marx y Engels, su concepción materialista de la historia. El Dr. Groß sólo ve en él “una obra maestra de habilidad agitativa”, habilidad que, sin embargo, no puede ser demasiado grande, porque “las perspectivas que ofrece el Manifiesto en el caso de que el comunismo llegue a gobernar son —al menos para los burgueses— nada menos que tentadoras”. Pues bien, Marx y Engels han expuesto en el Manifiesto los resultados de sus investigaciones, pero en el caso de los resultados de los trabajos científicos no se suele preguntar si son atractivos o no, sino si son correctos o no. El hecho de que el Dr. Groß no considere el Manifiesto como un documento histórico, sino como meramente agitativo, se debe, por tanto, a que lo ha entendido completamente mal. El “derecho” prescribe, la ciencia histórica constata: es obvio que allí donde el historiador constata un hecho, el jurista vea la exigencia del mismo. La visión del biógrafo se ha visto tan empañada por su forma jurídica de pensar que incluso allí donde el Manifiesto claramente constata, en lugar de exigir, él percibe detrás de la afirmación una tímida exigencia. Así llega también a la extraña opinión, que contradice directamente el contenido del Manifiesto, de que la demanda de la comunidad de mujeres está “siendo eludida de una manera peculiar, aunque en modo alguno se niega directamente”.</p>
                <p>La falta de sentido histórico puede atribuirse principalmente a que el autor haya malinterpretado la teoría del valor de Marx. También él ve en esta teoría “no sólo la proposición más importante del credo socialista, sino también el arma dialéctica más afilada de los socialistas”. En realidad, sin embargo, la teoría del valor de Marx no tiene nada que ver con el socialismo. “Marx nunca basó en esto sus reivindicaciones comunistas, sino en el colapso necesario del modo de producción capitalista, que se produce ante nuestros ojos cada día”, dice Engels en su prólogo a la traducción alemana de “La Miseria de la Filosofía”, (prólogo que también apareció en el “Neue Zeit”, edición de enero de 1885). La doctrina del valor no es la base del socialismo, sino la base de la economía capitalista actual. Con la refutación de la teoría del valor de Marx estaríamos lejos de refutar el socialismo; esta teoría no nos enseña a comprender el socialismo, sino los engranajes del capitalismo.</p>
                <p>Todos los economistas anteriores a Marx, y todos los que no lo entendieron después de él, han buscado una teoría del valor “en sí mismo”, una teoría del valor que fuera aplicable a todos los tiempos, pueblos y a todo lo que existe. Naturalmente, en la medida en que el valor de la mercancía no les parecía el valor “en sí mismo”, llegaron a teorías que, o bien son tan generales que no dicen nada, o bien se pierden por completo en una maraña de “síes” y “peros” y en una confusión de valor de uso y valor de cambio. Marx no malgastó sus fuerzas en una tarea tan ingrata. Examinó qué determina el valor de las mercancías, es decir, el valor de los bienes que los productores producen para la circulación y no para su propio uso. Esta ley del valor entonces sólo se aplica a las formas de sociedad que han desarrollado la producción de mercancías, y tanto más se aplica cuanto más la producción de mercancías se convierte en la forma exclusiva de producción. A Marx no se le ocurrió negar que la naturaleza ejercía una influencia inmensa en la producción de mercancías —no negaba en absoluto “la participación de las fuerzas de la naturaleza en la producción”, sino tan sólo su participación en la determinación del valor de las mercancías. En la medida que las objeciones a la teoría del valor de Marx no se basan en una confusión entre valor y precio, casi todas pueden atribuirse a la incomprensión de su carácter histórico, a la confusión de bien y mercancía[2]. El Sr. Groß también habla indistintamente a veces del valor de las “cosas”, otras del valor de las mercancías.</p>
                <p>El autor comparte tales errores con casi todos los representantes de la economía burguesa que han escrito sobre Marx y sus doctrinas. Sin embargo, se distingue favorablemente de la mayoría de ellos por la objetividad con la que trata de hacer justicia a su tarea. Allí donde el Sr. Groß se limita a disertar sin criticar, no se ha producido que sepamos un error notable. Destaca con razón “las investigaciones sobre la división del trabajo en sus diversas formas, así como sobre la importancia de la maquinaria” en ‘El capital’: “Estas partes de la obra de Marx figuran indiscutiblemente entre las más importantes que se han escrito en este sentido.” </p>
                <p>También la biografía de Marx está correctamente reproducida y contiene algunos detalles que hasta ahora eran desconocidos en sectores más amplios.</p>
                <p>En vista de ello, podemos permitirnos juzgar favorablemente el librito, tanto más cuando el propio autor no lo considera una biografía concluyente de Marx, sino sólo una contribución al esclarecimiento de las opiniones sobre él. Sin duda, servirá para eliminar algunos conceptos erróneos sobre Marx y para difundir el interés por sus enseñanzas a círculos más amplios. También será bien recibida por los seguidores de Marx que deseen acercarse a su personalidad. Sin embargo, no se puede pensar en una biografía concluyente de Marx y en una valoración completa y universal de sus enseñanzas antes de la publicación del segundo y tercer libro de ‘El capital’.</p>
                <p>K. Kautsky</p>
            
            </div>


			<!-- PIE DE PÁGINA -->
			<footer class="footer" id="footer">
				<div class="footer__about">
						<h3>Sobre nosotrxs</h2>
						<div class="footer__redes">
							<a href="https://twitter.com/ctrcultura"><img src="../assets/img/twitter.png" alt=""></a>
							<a href="https://www.instagram.com/ctrcultura/"><img src="../assets/img/instagram.png" alt=""></a>
							<a href="https://www.youtube.com/channel/UCn5WOCIpPjfzHLxYlhw1aeg"><img src="../assets/img/youtube.png" alt=""></a>
						</div>
				</div>
				<div class="footer__line"></div>
				<div class="footer__text">
					<p>Contracultura es un medio de divulgación y producción teórica con la intención de poder ser leído por amplias capas de la sociedad sin perder ni un ápice de rigor académico. Nuestro equipo gestor está conformado por estudiantes de posgrado del ámbito de la Ciencia Política y estudiantes egresados de grados universitarios como Ciencias Políticas, Economía y Psicología.</p>
				</div>
				<div class="footer__us">
					<a href="index_nosotrxs.php" class="footer__us-text">Consejo editorial</a>
					<a href="contacto.php" class="footer__us-text">Contacto</a>
					<a href="colabora.php" class="footer__us-text">Colabora</a>
					<a href="index_tienda.php" class="footer__us-text">Tienda online</a>
					<a href="index_librerias.php" class="footer__us-text">Librerias colaboradoras</a>
				</div>
				<div class="footer__final">				
				<p class="footer__name">En Contracultura creemos en el libro flujo de la información. Puede republicar nuestros artículos libremente, de manera impresa o digital, bajo la licencia Creative Commons. &copy; <?= date('Y') ?></p>
				</div>
			</footer>
		</div>
		<script src="..\js\index.js"></script>
	</body>
</html>